import 'package:flutter/material.dart';
import 'package:islami10/ui/quran/ChapterTitleWidget.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

class QuranTab extends StatelessWidget {
  List<String> names = [
    "الفاتحه",
    "البقرة",
    "آل عمران",
    "النساء",
    "المائدة",
    "الأنعام",
    "الأعراف",
    "الأنفال",
    "التوبة",
    "يونس",
    "هود",
    "يوسف",
    "الرعد",
    "إبراهيم",
    "الحجر",
    "النحل",
    "الإسراء",
    "الكهف",
    "مريم",
    "طه",
    "الأنبياء",
    "الحج",
    "المؤمنون",
    "النّور",
    "الفرقان",
    "الشعراء",
    "النّمل",
    "القصص",
    "العنكبوت",
    "الرّوم",
    "لقمان",
    "السجدة",
    "الأحزاب",
    "سبأ",
    "فاطر",
    "يس",
    "الصافات",
    "ص",
    "الزمر",
    "غافر",
    "فصّلت",
    "الشورى",
    "الزخرف",
    "الدّخان",
    "الجاثية",
    "الأحقاف",
    "محمد",
    "الفتح",
    "الحجرات",
    "ق",
    "الذاريات",
    "الطور",
    "النجم",
    "القمر",
    "الرحمن",
    "الواقعة",
    "الحديد",
    "المجادلة",
    "الحشر",
    "الممتحنة",
    "الصف",
    "الجمعة",
    "المنافقون",
    "التغابن",
    "الطلاق",
    "التحريم",
    "الملك",
    "القلم",
    "الحاقة",
    "المعارج",
    "نوح",
    "الجن",
    "المزّمّل",
    "المدّثر",
    "القيامة",
    "الإنسان",
    "المرسلات",
    "النبأ",
    "النازعات",
    "عبس",
    "التكوير",
    "الإنفطار",
    "المطفّفين",
    "الإنشقاق",
    "البروج",
    "الطارق",
    "الأعلى",
    "الغاشية",
    "الفجر",
    "البلد",
    "الشمس",
    "الليل",
    "الضحى",
    "الشرح",
    "التين",
    "العلق",
    "القدر",
    "البينة",
    "الزلزلة",
    "العاديات",
    "القارعة",
    "التكاثر",
    "العصر",
    "الهمزة",
    "الفيل",
    "قريش",
    "الماعون",
    "الكوثر",
    "الكافرون",
    "النصر",
    "المسد",
    "الإخلاص",
    "الفلق",
    "الناس"
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          Expanded(child: Image(image: AssetImage("assets/images/qur2an_screen_logo.png"))),
          Container(
            alignment: Alignment.center,
            padding: EdgeInsets.all(12),
            width: double.infinity,
            decoration: BoxDecoration(border: Border.symmetric(horizontal : BorderSide(color:Theme.of(context).colorScheme.secondary ,width: 2 ))),
            child: Text(AppLocalizations.of(context)!.chapter_name , style: TextStyle(fontSize: 25 , fontWeight: FontWeight.bold , color: Theme.of(context).colorScheme.onPrimary),),
          ),
          Expanded(
            flex: 3,
            child: ListView.separated(
                itemBuilder: (context, index) {
                  return ChapterTitleWidget(names[index] , index);
                },
                separatorBuilder: (context, index)=>
                  Container(
                    margin: EdgeInsets.symmetric(horizontal: 65),
                    color: Theme.of(context).colorScheme.secondary,
                    width: double.infinity,
                    height: 2,
                  )
                ,
                itemCount: names.length),
          )
        ],
      ),
    );
  }
}
